name: Build and Deploy

on:
  issues:
    types: [opened, edited, reopened, closed, deleted, labeled, unlabeled]

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Microblog
        uses: herschel666/microblog-action@KillYourMaster
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          url: 'https://herschel666.github.io/ddd'
          title: 'dddddddddddddd'
          description: 'Nothing to see here!'
          theme: 'tacit'
          pages: 'misc/*.md'
          posts-per-page: 3
          custom-styles: 'custom.css'
          label: 'blog'
          i18n.posts: 'Articles'

      - name: Deploy Microblog
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _site
          CLEAN: true
