name: Build and Deploy

on:
  issues:
    types: [opened, edited, reopened, closed, deleted]

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Microblog
        uses: herschel666/microbolog-action@eb388eca3c3d02f175634ae5dd146dde00d3dd6c
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          base-path: '/ddd/'
          title: 'dddddddddddddd'

      - name: Deploy Microblog
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _site
          CLEAN: true
